# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EstimationWidgetDesign.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_estimation(object):
    def setupUi(self, estimation):
        estimation.setObjectName("estimation")
        estimation.resize(800, 752)
        self.gridLayout = QtWidgets.QGridLayout(estimation)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plot_widget_dir = PlotWidget(estimation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget_dir.sizePolicy().hasHeightForWidth())
        self.plot_widget_dir.setSizePolicy(sizePolicy)
        self.plot_widget_dir.setMinimumSize(QtCore.QSize(400, 0))
        self.plot_widget_dir.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plot_widget_dir.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.plot_widget_dir.setObjectName("plot_widget_dir")
        self.verticalLayout_2.addWidget(self.plot_widget_dir)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtWidgets.QLabel(estimation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.spin_box_primeiro_cl = QtWidgets.QDoubleSpinBox(estimation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_box_primeiro_cl.sizePolicy().hasHeightForWidth())
        self.spin_box_primeiro_cl.setSizePolicy(sizePolicy)
        self.spin_box_primeiro_cl.setMinimumSize(QtCore.QSize(100, 0))
        self.spin_box_primeiro_cl.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spin_box_primeiro_cl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spin_box_primeiro_cl.setObjectName("spin_box_primeiro_cl")
        self.verticalLayout.addWidget(self.spin_box_primeiro_cl, 0, QtCore.Qt.AlignHCenter)
        self.label_11 = QtWidgets.QLabel(estimation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.spin_box_passo_cl = QtWidgets.QDoubleSpinBox(estimation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_box_passo_cl.sizePolicy().hasHeightForWidth())
        self.spin_box_passo_cl.setSizePolicy(sizePolicy)
        self.spin_box_passo_cl.setMinimumSize(QtCore.QSize(100, 0))
        self.spin_box_passo_cl.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spin_box_passo_cl.setObjectName("spin_box_passo_cl")
        self.verticalLayout.addWidget(self.spin_box_passo_cl, 0, QtCore.Qt.AlignHCenter)
        self.label_12 = QtWidgets.QLabel(estimation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.spin_box_ultimo_cl = QtWidgets.QDoubleSpinBox(estimation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_box_ultimo_cl.sizePolicy().hasHeightForWidth())
        self.spin_box_ultimo_cl.setSizePolicy(sizePolicy)
        self.spin_box_ultimo_cl.setMinimumSize(QtCore.QSize(100, 0))
        self.spin_box_ultimo_cl.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spin_box_ultimo_cl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spin_box_ultimo_cl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spin_box_ultimo_cl.setObjectName("spin_box_ultimo_cl")
        self.verticalLayout.addWidget(self.spin_box_ultimo_cl, 0, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(estimation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(2000000, 25))
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.combo_box_estimador = QtWidgets.QComboBox(estimation)
        self.combo_box_estimador.setObjectName("combo_box_estimador")
        self.verticalLayout.addWidget(self.combo_box_estimador)
        self.label_2 = QtWidgets.QLabel(estimation)
        self.label_2.setMaximumSize(QtCore.QSize(200000, 25))
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.combo_box_alg = QtWidgets.QComboBox(estimation)
        self.combo_box_alg.setObjectName("combo_box_alg")
        self.verticalLayout.addWidget(self.combo_box_alg)
        self.button_action_estimate = QtWidgets.QPushButton(estimation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_action_estimate.sizePolicy().hasHeightForWidth())
        self.button_action_estimate.setSizePolicy(sizePolicy)
        self.button_action_estimate.setMinimumSize(QtCore.QSize(0, 0))
        self.button_action_estimate.setObjectName("button_action_estimate")
        self.verticalLayout.addWidget(self.button_action_estimate)
        self.text_browser = QtWidgets.QTextBrowser(estimation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_browser.sizePolicy().hasHeightForWidth())
        self.text_browser.setSizePolicy(sizePolicy)
        self.text_browser.setMaximumSize(QtCore.QSize(400, 50))
        self.text_browser.setObjectName("text_browser")
        self.verticalLayout.addWidget(self.text_browser, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 2, 4)
        self.plot_widget_esq = PlotWidget(estimation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget_esq.sizePolicy().hasHeightForWidth())
        self.plot_widget_esq.setSizePolicy(sizePolicy)
        self.plot_widget_esq.setMaximumSize(QtCore.QSize(16777215, 2200))
        self.plot_widget_esq.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.plot_widget_esq.setObjectName("plot_widget_esq")
        self.gridLayout.addWidget(self.plot_widget_esq, 3, 0, 1, 4)

        self.retranslateUi(estimation)
        QtCore.QMetaObject.connectSlotsByName(estimation)

    def retranslateUi(self, estimation):
        _translate = QtCore.QCoreApplication.translate
        estimation.setWindowTitle(_translate("estimation", "Form"))
        self.label_10.setText(_translate("estimation", "First step"))
        self.label_11.setText(_translate("estimation", "Number of steps"))
        self.label_12.setText(_translate("estimation", "Last step"))
        self.label.setText(_translate("estimation", "Metric"))
        self.label_2.setText(_translate("estimation", "Imaging Algorithm"))
        self.button_action_estimate.setText(_translate("estimation", "Estimate"))
from pyqtgraph import PlotWidget
