# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SurfaceEstimationWidgetDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 752)
        Form.setMinimumSize(QtCore.QSize(800, 752))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.button_estimate = QtWidgets.QPushButton(Form)
        self.button_estimate.setObjectName("button_estimate")
        self.gridLayout.addWidget(self.button_estimate, 2, 1, 1, 1)
        self.gl_widget = GLViewWidget(Form)
        self.gl_widget.setMinimumSize(QtCore.QSize(400, 300))
        self.gl_widget.setObjectName("gl_widget")
        self.gridLayout.addWidget(self.gl_widget, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(153, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(154, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.parameter_tree = ParameterTree(self.frame)
        self.parameter_tree.setGeometry(QtCore.QRect(0, 0, 401, 341))
        self.parameter_tree.setMinimumSize(QtCore.QSize(400, 341))
        self.parameter_tree.setObjectName("parameter_tree")
        self.ref_text = QtWidgets.QLabel(self.frame)
        self.ref_text.setGeometry(QtCore.QRect(430, 10, 131, 22))
        self.ref_text.setMinimumSize(QtCore.QSize(131, 22))
        self.ref_text.setObjectName("ref_text")
        self.depth = QtWidgets.QLabel(self.frame)
        self.depth.setGeometry(QtCore.QRect(560, 10, 67, 22))
        self.depth.setText("")
        self.depth.setObjectName("depth")
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_estimate.setText(_translate("Form", "Estimate"))
        self.ref_text.setText(_translate("Form", "Minimum Depth:"))
from pyqtgraph.opengl import GLViewWidget
from pyqtgraph.parametertree import ParameterTree


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
